window.booksData = [
    { id: 1, title: 'The Alchemist', author: 'Paulo Coelho', genre: 'Fiction', price: 199, image: 'img/book-img/The Alchemist.jpg' },
    { id: 2, title: 'Madonna in a Fur Coat', author: 'Sabahattin Ali', genre: 'Fiction', price: 129, image: 'img/book-img/Madonna in a Fur Coat.jpg' },
    { id: 3, title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', genre: 'Classic', price: 179, image: 'img/book-img/Crime and Punishment.jpg' },
    { id: 4, title: 'İnce Memed', author: 'Yaşar Kemal', genre: 'Fiction', price: 149, image: 'img/book-img/İnce Memed.jpg' },
    { id: 5, title: '1984', author: 'George Orwell', genre: 'Dystopia', price: 139, image: 'img/book-img/1984.jpg' },
    { id: 6, title: 'Animal Farm', author: 'George Orwell', genre: 'Fiction', price: 119, image: 'img/book-img/Animal Farm.jpg' },
    { id: 7, title: 'Pride and Prejudice', author: 'Jane Austen', genre: 'Romance', price: 159, image: 'img/book-img/Pride and Prejudice.jpg' },
    { id: 8, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', genre: 'Classic', price: 139, image: 'img/book-img/The Great Gatsby.jpg' },
    { id: 9, title: 'To Kill a Mockingbird', author: 'Harper Lee', genre: 'Classic', price: 169, image: 'img/book-img/To Kill a Mockingbird.jpg' },
    { id: 10, title: 'The Catcher in the Rye', author: 'J.D. Salinger', genre: 'Fiction', price: 149, image: 'img/book-img/The Catcher in the Rye.jpg' },
    { id: 11, title: 'The Hobbit', author: 'J.R.R. Tolkien', genre: 'Fantasy', price: 189, image: 'img/book-img/The Hobbit.jpg' },
    { id: 12, title: 'Harry Potter', author: 'J.K. Rowling', genre: 'Fantasy', price: 199, image: 'img/book-img/Harry Potter.jpg' },
    { id: 13, title: 'Sherlock Holmes', author: 'Arthur Conan Doyle', genre: 'Mystery', price: 159, image: 'img/book-img/The Adventures Of Sherlock Holmes.jpg' },
    { id: 14, title: 'The Da Vinci Code', author: 'Dan Brown', genre: 'Mystery', price: 179, image: 'img/book-img/The Da Vinci Code.jpg' },
    { id: 15, title: 'Steve Jobs', author: 'Walter Isaacson', genre: 'Biography', price: 249, image: 'img/book-img/Steve Jobs.jpg' },
    { id: 16, title: 'Sapiens', author: 'Yuval Noah Harari', genre: 'History', price: 229, image: 'img/book-img/Sapiens.jpg' },
    { id: 17, title: 'Atomic Habits', author: 'James Clear', genre: 'Self-Help', price: 189, image: 'img/book-img/Atomic Habits.jpg' },
    { id: 18, title: 'The Power of Now', author: 'Eckhart Tolle', genre: 'Self-Help', price: 169, image: 'img/book-img/The Power of Now.jpg' },
    { id: 19, title: 'Dune', author: 'Frank Herbert', genre: 'Science Fiction', price: 209, image: 'img/book-img/Dune.jpg' },
    { id: 20, title: 'Foundation', author: 'Isaac Asimov', genre: 'Science Fiction', price: 199, image: 'img/book-img/Foundation.jpg' }
];